### ISSUE TITLE
[ SignUp ] 회원가입 페이지 구현 및 레이아웃 작업

### ISSUE THREAD

**Issue by dev-junehee** [MINI-TEAM3/client#16]
## Todo
- [x] 상단 타이틀 배치
- [x] 컨테이너 위치 정렬 (상위 컴포넌트에서 해결)
- [x] 가입 정보 `input` 배치 (이메일, 비밀번호, 비밀번호 확인) 총 3개
- [x] 유저 정보 `input` 배치 (이름, 병원명, 파트, 연락처) 총 4개
- [x] `input` placeholder 추가
- [x] 회원가입 버튼 배치
- [x] 회원가입 API 기능 연결
- [x] 회원가입 완료 시 로그인 페이지 연결
- [x] 하단 로그인 버튼에 로그인 페이지 연결 (이미 계정 있는 경우)
- [x] 에러 핸들링
- [x] 미사용 코드 제거 및 최종 확인

## 참고자료
- 브랜치명 `feature-signup`
- [react-hook-form](https://www.react-hook-form.com/) 라이브러리 사용 예정
