### ISSUE TITLE
[ Modal ] 모달 컴포넌트 생성

### ISSUE THREAD

**Issue by doitidey** [MINI-TEAM3/client#28]
## Todo
- [x] 리코일을 이용하여 재사용 전역 모달 생성
- [x] 당직 변경 신청 모달 ui
- [x] 사이드바 버튼과 연결
- [x] 휴가 신청 모달 ui
- [x] 사이드바 버튼과 연결
- [ ] 금일 당직 모달 ui
- [x] 캘린더와 연결
- [ ] 금일 휴가 모달 ui
- [x] 캘린더와 연결

## 참고자료
브랜치 명: `feature-modal`
- [recoil을 사용한 전역 모달 관리(with TypeScript)](https://leego.tistory.com/entry/recoil%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%A0%84%EC%97%AD-%EB%AA%A8%EB%8B%AC-%EA%B4%80%EB%A6%ACwith-TypeScript)
- [재사용 전역 모달 만들기](https://lasbe.tistory.com/148)
