### ISSUE TITLE
[ Components ] SideBar 레이아웃 구성, 기능 구현 

### ISSUE THREAD

**Issue by 7581058** [MINI-TEAM3/client#5]
## Todo

**레이아웃**
- [x] 로고 배치 => 공식 로고로 배치
- [x] 아이콘 + 메뉴 배치 
- [x] 휴가신청, 당직 수정 버튼 배치(공통버튼나오면)
- [x] 사용자 이름, 과 직급 배치 
- [x] 사용자 남은 연차일 배치 
- [x] 사용자 이번달 당직 근무 일수 배치
- [x] 로그아웃 버튼 배치 
- [x] 마크?하단에 배치 

**기능구현(MockData사용)**
- [x] 각 메뉴 페이지로 연결 
- [x] 사용자 이름, 과 직급 출력 
- [x] 사용자 남은 연차일 그래프로 출력
- [x] 사용자 이번달 당직 근무 일수 그래프로 출력 
- [x] MockData 적용 후 ts오류 해결 
- [x] 휴가 신청 버튼 클릭 시 휴가 신청 모달 열기 (-> 휴가 신청)
- [x] 당직 수정 버튼 클릭 시 당직 수정 모달 열기 (-> 당직 변경 신청)

**기능구현 추가사항**
- [x] 개인정보수정 -> 마이페이지로 변경 
- [x] 마이페이지 active일때 개인정보수정, 비밀번호수정 서브메뉴 보이기
- [x] 서브메뉴 active 
- [x] 서브메뉴 화면 연결
- [x] 로그아웃 시 로그인된 토큰 날리기 
- [x] 로그아웃 시 로그인 페이지로 이동 

**수정사항**
- [x] 정보출력 화면 침범 수정 
- [x] json 데이터로 테스트 변경 

**api적용**
- [x] 로그인된 유저 정보 전역상태또는쿼리로 관리 
- [x] 사용자 이름, 과 직급 출력 
- [x] 사용자 남은 연차일 그래프로 출력
- [x] 사용자 이번달 당직 근무 일수 그래프로 출력 
- [x] 휴가 신청 버튼 클릭 시 휴가 신청 모달 열기 -> 휴가 신청 
- [x] 당직 수정 버튼 클릭 시 당직 수정 모달 열기 -> 당직 변경 신청

## 참고자료
-브랜치: feature-sidebar
-MockData 참고 api `마이페이지 /user/myPage/{id}`
