### ISSUE TITLE
[ SideBar, Header ] 버튼 추가, 타이머 추가

### ISSUE THREAD

**Issue by doitidey** [MINI-TEAM3/client#69]
## Todo
- [x] 헤더에 타이머 기능을 추가합니다.
  - [x] 상태에 따라 on, off가 바뀝니다.
  - [x] api를 연결합니다.
- [x] 사이드 바 버튼들을 재정렬하고, 출퇴근 체크가 가능한 버튼을 추가합니다.
  - [x] 버튼 컴포넌트를 재정비합니다.
  - [x] api를 연결합니다.
