### ISSUE TITLE
[ Settings ] 전역 스타일 수정

### ISSUE THREAD

**Issue by dev-junehee** [MINI-TEAM3/client#7]
## Todo
- [x] `<button>` font-family 적용
- [x] `<body>` background-color 적용
- [x] `:root { margin: 0; }` 수정

## 참고자료
- 브랜치명 `feature-globalstyle`

**Comment by dev-junehee** [comment]
2023.07.27(목) 구현 완료
