### ISSUE TITLE
[ Setting ] huscky 적용

### ISSUE THREAD

**Issue by doitidey** [MINI-TEAM3/client#96]
## Todo
- [x] 허스키 설치 및 적용
- [x] lint, prettier 기존 협의된 컨벤션 사용
- [x] 커밋, push 시 husky 자동 실행
